import type { Metadata } from 'next'
import './globals.css'
import { soria, generalSans } from '@/utils/fonts'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Mandy Thorel - Portfolio',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="icon" href="/assets/logomdytrl.svg" sizes="88px" />
      </head>
      <body className={`${soria.variable} ${generalSans.variable}`}>
        <Navbar />
        <div className="mx-80 pt-12">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
